version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/src
      - ./.tmp/go/pkg:/go/pkg
      - ./.tmp/go/cache:/.cache
      - ./.tmp/mmake:/usr/local/include/github.com
    environment:
      - DYNAMO_URL=http://dynamodb:8000
      - POSTGRES_URL=postgres://user:password@postgres/indebted?sslmode=disable
    depends_on:
      - dynamodb
      - postgres

  dynamodb:
    image: amazon/dynamodb-local:1.11.477

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indebted
