version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/src
      - ./.tmp/go/pkg:/go/pkg
      - ./.tmp/go/cache:/.cache
      - ./.tmp/mmake:/usr/local/include/github.com
    environment:
      - DYNAMO_URL=http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local:1.11.477

  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: event-store-test
    ports:
      - 3306:3306
