steps:
  - name: test
    command:
      - make go-mod-verify
      - make check-fmt
      - make lint
      - dockerize -wait http://dynamodb:8000/shell/ -timeout 60s
      - DYNAMO_URL=http://dynamodb:8000 make test
    plugins:
      - docker#v3.3.0:
          image: indebted-test
          network: indebted-net
