steps:
  - name: test
    command:
      - make check-fmt
      - make lint
      - dockerize -wait http://dynamodb:8000/shell/ -timeout 60s
      - DYNAMO_URL=http://dynamodb:8000 make test
    plugins:
      - docker-compose#v3.1.0:
          run: test
          config: .buildkite/docker-compose.yml
